version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: ols-wp-webserver
    AWS_DEFAULT_REGION: us-east-2
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Account ID: $ACCOUNT_ID"
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Repository URI: $REPO_URI"
      - aws ecr create-repository --repository-name $IMAGE_REPO_NAME --region $AWS_DEFAULT_REGION || echo "Repository already exists"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $REPO_URI:$IMAGE_TAG
